version: "3.4"

x-common-variables: &common-variables
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: freelance_ai
  REACT_APP_SERVER_PORT: 5000

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
    ports:
      - 13306:3306
    restart: unless-stopped
    volumes:
      - ./sql/freelance_ai_schema.sql:/docker-entrypoint-initdb.d/freelance_ai_schema.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./ra_ai
    depends_on:
      - mysql
    expose:
      - 5000
      - 3000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 5000:5000
      - 3000:3000
    links:
      - mysql
    command: npm run dev
