version: "3.4"

x-common-variables: &common-variables
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: freelance_ai
  REACT_APP_SERVER_PORT: 5000

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=freelance_ai
    ports:
      - 3306:3306
    expose:
      - 3306
  # phpmyadmin:
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #   links:
  #     - mysql:mysql
  #   ports:
  #     - 8080:80
  #   restart: always
  server:
    build: ./ra_ai
    depends_on:
      - mysql
    expose:
      - 5000
      - 3000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 5000:5000
      - 3000:3000
    links:
      - mysql
    command: npm run dev
